ALTER TABLE chapter 
  ADD CONSTRAINT FOREIGN KEY (bookId) REFERENCES books (id);

ALTER TABLE CHAPTERWORDS 
    ADD CONSTRAINT FOREIGN KEY (chapterId) REFERENCES chapter (id);

ALTER TABLE CHAPTERWORDS 
    ADD CONSTRAINT FOREIGN KEY (wordId) REFERENCES words (id);

ALTER TABLE chapterPhrasesXref 
    ADD CONSTRAINT FOREIGN KEY (chapterId) REFERENCES chapter (id);

ALTER TABLE chapterPhrasesXref 
    ADD CONSTRAINT FOREIGN KEY (phraseId) REFERENCES phrases (id);