ALTER TABLE `books`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `chapter`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `chapterPhrasesXref`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `CHAPTERWORDS`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `knownStatus`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `phrases`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `words`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;